### ISSUE TITLE
Bury message disappears while revived at same time

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#435] opened 2018-12-20 13:43 UTC
In [this room](https://jinrou.uhyohyo.net/room/138682) at sunrising of day 3, player ロビン was posioned and revived by あまでうぴ☆ at same time. However, only the reviving message came out, the bury message disappeared.

**Comment by Sunev** [comment] 2018-12-20 16:39
And I'm wander is it a good idea to let Cat to revive a player who was dead but not found.

**Comment by uhyo** [comment] 2018-12-21 04:09
Thank you, but it's a duplicate of #430.

**Closed by uhyo** 2018-12-21 04:09 UTC
